# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cg_cpp <- function(A, b, B) {
    .Call('_matopscpp_cg_cpp', PACKAGE = 'matopscpp', A, b, B)
}

mmult <- function(m1, m2) {
    .Call('_matopscpp_mmult', PACKAGE = 'matopscpp', m1, m2)
}

